name: build prod

on:
  workflow_dispatch:
  workflow_call:

jobs:

  build:
    name: build image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: init alpine
        uses: jirutka/setup-alpine@v1
        with:
          branch: v3.20
      - name: run build with alpine
        shell: alpine.sh --root {0}
        run: |
            ln -s ./core /opt/core
            cd /opt/core
            sh go-build.sh
