name: build prod

on:
  workflow_dispatch:
  workflow_call:

jobs:

  build:
    name: build image
    runs-on: ubuntu-latest
    env:
      BASE_WORKSPACE: ${{ github.workspace }}
    steps:
      - uses: actions/checkout@v5
      - name: init alpine
        uses: jirutka/setup-alpine@v1
        with:
          branch: v3.20
      - name: create ln
        run: |
            ln -snf ${{ env.BASE_WORKSPACE }}/core /opt
            ls /opt/core/
            echo "------------------------------------------"
            ls ./core 
      - name: run build with alpine
        shell: alpine.sh --root {0}
        run: |
            cd /opt/core
            sh go-build.sh
